### ISSUE TITLE
还在维护么，

### ISSUE THREAD

**Issue by mxyblog** [SuperTylerX/wordpress-to-uniapp#3]
前端茶会线上小程序不是最新的么？没有看到圈子。登陆没有作用，点赞也提示 /wp-json/uni-app-rest-enhanced/v1/post/like 未找到匹配URL和请求方式的路由，有详细一点的使用说明么？

**Comment by SuperTylerX** [comment]
谢谢对本项目支持。前端茶会是个人小程序，无法上线社交属性的圈子功能，最新的小程序我提交到“星荧WordPress”上了，可以搜索看下。接口部分可能最新的几次改动我没有推上来，迟点看一下这个问题。

**Comment by mxyblog** [comment]
嗯 已搜到 感谢回复。期待更新！
